### ISSUE TITLE
AttributeError: Get_trade_bot(botguid:str)

### ISSUE THREAD

**Issue by lou565** [haasome-tools/haasomeapi#1]
When calling the get_trade_bot function with the guid of a bot  the follwing exception is thrown:

bot = haasclient.tradeBotApi.get_trade_bot(bot.guid)
File "/usr/lib/python3.6/site-packages/haasomeapi/apis/TradeBotApi.py", line 109, in get_trade_bot
response = self.get_all_bots()

AttributeError: 'TradeBotApi' object has no attribute 'get_all_bots'

**Comment by R4stl1n** [comment]
Fixed in merge request #4 by lou565
