### ISSUE TITLE
Can't send the TemplateGUID on a Pingpong bot setup

### ISSUE THREAD

**Issue by msylvestre** [haasome-tools/haasomeapi#9]
Hi guys ! Trying to use the API here to create a pingpong bot and I get a funky error on the haasome.customBotApi.setup_ping_pong_bot() call.    I sent the 11 param needed which doesn't include a templateGuid.

And the response is: 
Parameter missing: templateGuid
EnumErrorCode.INVALID_PARAMETER

interestingly enough, the scalperBot has a param to set the template, and I have no issue with that endpoint.

And finally, when you look at the API doc on haasonline, we see 12 param, which require a templateGuid, but no word on where to find the definition of those "template"

https://help.haasonline.com/api/api-endpoints/custom-trade-bot-api#setup-pingpong-bot

*Repro Step*
```
    accountGuid = "xxxx-zzzz-yyyy"
    newPingPong = haasome.customBotApi.new_custom_bot(accountGuid, EnumCustomBotType.PING_PONG_BOT,"MS25 - PP Bot", "BNB", "BTC", "")
    pingPongEdited = haasome.customBotApi.setup_ping_pong_bot(accountGuid, newPingPong.result.guid, "MS25 - new name", "BNB", "BTC",  "", 0.0, EnumBotTradeAmount.STATIC, 0.3, "BTC", 0.2)
```

*Result*
```
Parameter missing: templateGuid
EnumErrorCode.INVALID_PARAMETER
```

**Comment by R4stl1n** [comment]
Fixed with merge #10
